-- Ingestion Phase 0: source intelligence.
--
-- Hand-written rather than generated by `migrate dev`. This database carries
-- objects Prisma does not know about — the GENERATED tsvector column, the
-- partial indexes, the NULLS NOT DISTINCT constraints from
-- migrations/manual/001_raw_constraints.sql. Both `migrate dev` and `db push`
-- diff the schema against the database and would offer to DROP every one of
-- them. Writing the additive DDL by hand and applying it with `migrate deploy`
-- touches nothing that already exists.

-- CreateEnum
CREATE TYPE "SourceKind" AS ENUM ('HTML', 'PDF', 'JSON', 'RSS');

-- CreateEnum
CREATE TYPE "SourceStatus" AS ENUM ('ACTIVE', 'PAUSED', 'FAILING', 'DEAD');

-- CreateEnum
CREATE TYPE "FetchOutcome" AS ENUM (
  'CHANGED', 'UNCHANGED', 'NOT_MODIFIED', 'HTTP_ERROR', 'NETWORK_ERROR', 'BLOCKED_BY_ROBOTS'
);

-- CreateTable
CREATE TABLE "Source" (
    "id" TEXT NOT NULL,
    "siteId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "authority" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "kind" "SourceKind" NOT NULL DEFAULT 'HTML',
    "status" "SourceStatus" NOT NULL DEFAULT 'ACTIVE',
    "cadenceMinutes" INTEGER NOT NULL DEFAULT 180,
    "robotsAllowed" BOOLEAN,
    "robotsCheckedAt" TIMESTAMP(3),
    "lastFetchedAt" TIMESTAMP(3),
    "lastHash" TEXT,
    "lastOutcome" "FetchOutcome",
    "consecutiveFailures" INTEGER NOT NULL DEFAULT 0,
    "etag" TEXT,
    "lastModified" TEXT,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Source_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "SourceSnapshot" (
    "id" TEXT NOT NULL,
    "sourceId" TEXT NOT NULL,
    "fetchedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "outcome" "FetchOutcome" NOT NULL,
    "httpStatus" INTEGER,
    "durationMs" INTEGER,
    "contentHash" TEXT,
    "contentType" TEXT,
    "contentBytes" INTEGER,
    "etag" TEXT,
    "lastModified" TEXT,
    "rawContent" TEXT,
    "rawTruncated" BOOLEAN NOT NULL DEFAULT false,
    "rawLocation" TEXT,
    "error" TEXT,

    CONSTRAINT "SourceSnapshot_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Source_siteId_url_key" ON "Source"("siteId", "url");

-- CreateIndex: the scheduler's only query — active sources whose poll is due.
CREATE INDEX "Source_status_lastFetchedAt_idx" ON "Source"("status", "lastFetchedAt");

-- CreateIndex
CREATE INDEX "Source_authority_idx" ON "Source"("authority");

-- CreateIndex: a single source's timeline, newest first.
CREATE INDEX "SourceSnapshot_sourceId_fetchedAt_idx" ON "SourceSnapshot"("sourceId", "fetchedAt" DESC);

-- CreateIndex: "what changed across everything last night".
CREATE INDEX "SourceSnapshot_outcome_fetchedAt_idx" ON "SourceSnapshot"("outcome", "fetchedAt" DESC);

-- AddForeignKey
ALTER TABLE "Source" ADD CONSTRAINT "Source_siteId_fkey"
  FOREIGN KEY ("siteId") REFERENCES "Site"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SourceSnapshot" ADD CONSTRAINT "SourceSnapshot_sourceId_fkey"
  FOREIGN KEY ("sourceId") REFERENCES "Source"("id") ON DELETE CASCADE ON UPDATE CASCADE;
